// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2N8AKFqb8wrlNKg93P2JE0AuueWLlIaw',
    appId: '1:240368677379:web:7bcfb213e55794c302d436',
    messagingSenderId: '240368677379',
    projectId: 'bluvoyage',
    authDomain: 'bluvoyage.firebaseapp.com',
    storageBucket: 'bluvoyage.firebasestorage.app',
    measurementId: 'G-1RS1MY6632',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7TOCCthayXdaxH5N0LQljKNO2beSqo4',
    appId: '1:240368677379:android:05518001f2ab73db02d436',
    messagingSenderId: '240368677379',
    projectId: 'bluvoyage',
    storageBucket: 'bluvoyage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-LRTl8xQbgdnPW2wJAmGef6BShFxpYk',
    appId: '1:240368677379:ios:5ba1a92ae3e8ccec02d436',
    messagingSenderId: '240368677379',
    projectId: 'bluvoyage',
    storageBucket: 'bluvoyage.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-LRTl8xQbgdnPW2wJAmGef6BShFxpYk',
    appId: '1:240368677379:ios:5ba1a92ae3e8ccec02d436',
    messagingSenderId: '240368677379',
    projectId: 'bluvoyage',
    storageBucket: 'bluvoyage.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2N8AKFqb8wrlNKg93P2JE0AuueWLlIaw',
    appId: '1:240368677379:web:1a67f6433792fae802d436',
    messagingSenderId: '240368677379',
    projectId: 'bluvoyage',
    authDomain: 'bluvoyage.firebaseapp.com',
    storageBucket: 'bluvoyage.firebasestorage.app',
    measurementId: 'G-0EJSN122DR',
  );
}
